/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./components/AppLink.vue')['default']
    BackLink: typeof import('./components/BackLink.vue')['default']
    Debug: typeof import('./components/Debug.vue')['default']
    EditEntry: typeof import('./components/EditEntry.vue')['default']
    ILucideChevronUp: typeof import('~icons/lucide/chevron-up')['default']
    ILucideCircleMinus: typeof import('~icons/lucide/circle-minus')['default']
    ILucideCirclePlus: typeof import('~icons/lucide/circle-plus')['default']
    ILucideClipboard: typeof import('~icons/lucide/clipboard')['default']
    ILucideClipboardPaste: typeof import('~icons/lucide/clipboard-paste')['default']
    ILucideClock: typeof import('~icons/lucide/clock')['default']
    ILucideDownload: typeof import('~icons/lucide/download')['default']
    ILucideGithub: typeof import('~icons/lucide/github')['default']
    ILucideImport: typeof import('~icons/lucide/import')['default']
    ILucideInfo: typeof import('~icons/lucide/info')['default']
    ILucideLetterText: typeof import('~icons/lucide/letter-text')['default']
    ILucideLoaderCircle: typeof import('~icons/lucide/loader-circle')['default']
    ILucidePalette: typeof import('~icons/lucide/palette')['default']
    ILucideSave: typeof import('~icons/lucide/save')['default']
    ILucideScaling: typeof import('~icons/lucide/scaling')['default']
    ILucideTrash2: typeof import('~icons/lucide/trash2')['default']
    ILucideUndo: typeof import('~icons/lucide/undo')['default']
    ILucideX: typeof import('~icons/lucide/x')['default']
    LogLine: typeof import('./components/LogLine.vue')['default']
    LogToast: typeof import('./components/LogToast.vue')['default']
    MessageButtons: typeof import('./components/MessageButtons.vue')['default']
    MonacoEditor: typeof import('./components/MonacoEditor.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    NotFound: typeof import('./components/NotFound.vue')['default']
    PopoverMenu: typeof import('./components/PopoverMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./components/ThemeSwitch.vue')['default']
  }
}
