/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./components/AppLink.vue')['default']
    BackLink: typeof import('./components/BackLink.vue')['default']
    Debug: typeof import('./components/Debug.vue')['default']
    ILucideCircleMinus: typeof import('~icons/lucide/circle-minus')['default']
    ILucideCirclePlus: typeof import('~icons/lucide/circle-plus')['default']
    ILucideInfo: typeof import('~icons/lucide/info')['default']
    ILucideLoaderCircle: typeof import('~icons/lucide/loader-circle')['default']
    ILucideX: typeof import('~icons/lucide/x')['default']
    MessageButtons: typeof import('./components/MessageButtons.vue')['default']
    MonacoEditor: typeof import('./components/MonacoEditor.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    NotFound: typeof import('./components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./components/ThemeSwitch.vue')['default']
  }
}
