/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./../components/App.vue')['default']
    AppLink: typeof import('./../components/AppLink.vue')['default']
    BackLink: typeof import('./../components/BackLink.vue')['default']
    Changelog: typeof import('./../components/Changelog.vue')['default']
    Debug: typeof import('./../components/Debug.vue')['default']
    EyeDropper: typeof import('./../components/EyeDropper.vue')['default']
    NavLink: typeof import('./../components/NavLink.vue')['default']
    NotFound: typeof import('./../components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
