/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/common/about': RouteRecordInfo<'/common/about', '/common/about', Record<never, never>, Record<never, never>>,
    '/iframe/': RouteRecordInfo<'/iframe/', '/iframe', Record<never, never>, Record<never, never>>,
    '/options/': RouteRecordInfo<'/options/', '/options', Record<never, never>, Record<never, never>>,
    '/options/[...path]': RouteRecordInfo<'/options/[...path]', '/options/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/options/about': RouteRecordInfo<'/options/about', '/options/about', Record<never, never>, Record<never, never>>,
    '/popup/': RouteRecordInfo<'/popup/', '/popup', Record<never, never>, Record<never, never>>,
    '/setup/install': RouteRecordInfo<'/setup/install', '/setup/install', Record<never, never>, Record<never, never>>,
    '/setup/update': RouteRecordInfo<'/setup/update', '/setup/update', Record<never, never>, Record<never, never>>,
  }
}
