/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/content': RouteRecordInfo<'/content', '/content', Record<never, never>, Record<never, never>>,
    '/install': RouteRecordInfo<'/install', '/install', Record<never, never>, Record<never, never>>,
    '/options': RouteRecordInfo<'/options', '/options', Record<never, never>, Record<never, never>>,
    '/options/': RouteRecordInfo<'/options/', '/options', Record<never, never>, Record<never, never>>,
    '/options/[...path]': RouteRecordInfo<'/options/[...path]', '/options/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/options/about': RouteRecordInfo<'/options/about', '/options/about', Record<never, never>, Record<never, never>>,
    '/options/something': RouteRecordInfo<'/options/something', '/options/something', Record<never, never>, Record<never, never>>,
    '/popup': RouteRecordInfo<'/popup', '/popup', Record<never, never>, Record<never, never>>,
    '/popup/': RouteRecordInfo<'/popup/', '/popup', Record<never, never>, Record<never, never>>,
    '/popup/about': RouteRecordInfo<'/popup/about', '/popup/about', Record<never, never>, Record<never, never>>,
    '/update': RouteRecordInfo<'/update', '/update', Record<never, never>, Record<never, never>>,
  }
}
